name: Build and Publish to NPM
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      
      - name: Setup node 🔨
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Publish to NPM 🚀
        run: cd dist/ngx-diff2html && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
